credentials:
  usernames:
    kjy:
      email: 15801386755@163.com
      name: Jingyi Kang
      password: 123
      level: 1
    trihook:
      email: xxxx@163.com
      name: Jianjun Jiang
      password: 123
      level: 1
    seven:
      email: xxxx@163.com
      name: Yawen Zhang
      password: 123
      level: 1
    yifan:
      email: xxxx@163.com
      name: Yifan He
      password: 123
      level: 1
    aki:
      email: 15801386755@163.com
      name: Aki
      password: 456
      level: 2
    zs:
      email: 15801386755@163.com
      name: Zhang san
      password: 789
      level: 3
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - 123@111.com