cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    aki:
      email: 15801386755@163.com
      level: 4
      name: Aki
      password: 456
    kjy:
      email: 15801386755@163.com
      level: 1
      name: Jingyi Kang
      password: 123
    seven:
      email: xxxx@163.com
      level: 1
      name: Yawen Zhang
      password: 123
    trihook:
      email: xxxx@163.com
      level: 1
      name: Jianjun Jiang
      password: 123
    yifan:
      email: xxxx@163.com
      level: 1
      name: Yifan He
      password: 123
    zs:
      email: 15801386755@163.com
      level: 3
      name: Zhang san
      password: 789
preauthorized:
  emails:
  - 123@111.com
