credentials:
  usernames:
    aki:
      project:
      - c
      - d
    kjy:
      project:
      - a
      - b
      - c
      - kk
      - kkkk
    zs:
      project:
      - d
    trihook:
      project:
      - a
      - b
      - c
    seven:
      project:
        - a
        - b
        - c
    yifan:
      project:
        - a
        - b
        - c
