credentials:
  usernames:
    aki:
      project:
        CNN:
        - a
        Segment:
        - aa
    kjy:
      project:
        CNN:
        - a
        - b
        Segment:
        - aa
    seven:
      project:
        CNN:
        - a
        Segment:
        - aa
    trihook:
      project:
        CNN:
        - a
        Segment:
        - aa
    yifan:
      project:
        CNN:
        - a
        Segment:
        - aa
    zs:
      project:
        CNN:
        - a
        Segment:
        - aa
