Project:
  name:
    a:
      loss: 0
      test_acc: 0
      val_acc: 0.7794522725952484
    aa:
      loss: 0
      test_acc: 0
      val_acc: 0
    b:
      loss: 0
      test_acc: 0
      val_acc: 0
    c:
      loss: 0
      test_acc: 0
      val_acc: 0
